// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MutexServiceClient is the client API for MutexService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutexServiceClient interface {
	PassToken(ctx context.Context, in *TokenMessage, opts ...grpc.CallOption) (*TokenReply, error)
}

type mutexServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMutexServiceClient(cc grpc.ClientConnInterface) MutexServiceClient {
	return &mutexServiceClient{cc}
}

func (c *mutexServiceClient) PassToken(ctx context.Context, in *TokenMessage, opts ...grpc.CallOption) (*TokenReply, error) {
	out := new(TokenReply)
	err := c.cc.Invoke(ctx, "/mutex.MutexService/PassToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutexServiceServer is the server API for MutexService service.
// All implementations must embed UnimplementedMutexServiceServer
// for forward compatibility
type MutexServiceServer interface {
	PassToken(context.Context, *TokenMessage) (*TokenReply, error)
	mustEmbedUnimplementedMutexServiceServer()
}

// UnimplementedMutexServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMutexServiceServer struct {
}

func (UnimplementedMutexServiceServer) PassToken(context.Context, *TokenMessage) (*TokenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PassToken not implemented")
}
func (UnimplementedMutexServiceServer) mustEmbedUnimplementedMutexServiceServer() {}

// UnsafeMutexServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutexServiceServer will
// result in compilation errors.
type UnsafeMutexServiceServer interface {
	mustEmbedUnimplementedMutexServiceServer()
}

func RegisterMutexServiceServer(s grpc.ServiceRegistrar, srv MutexServiceServer) {
	s.RegisterService(&MutexService_ServiceDesc, srv)
}

func _MutexService_PassToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutexServiceServer).PassToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mutex.MutexService/PassToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutexServiceServer).PassToken(ctx, req.(*TokenMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// MutexService_ServiceDesc is the grpc.ServiceDesc for MutexService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutexService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mutex.MutexService",
	HandlerType: (*MutexServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PassToken",
			Handler:    _MutexService_PassToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
